#!/bin/bash

cd /var/www/hoyga/r

reddits="programming;100
hitchhiking;9
thoriumreactor;6
DIY;1500
woodworking;1200
AskHistorians;800
DepthHub;200
Futurology;1000
europe;300
Showerthoughts;3000
budgetfood;50
UKFrugal;5
gamedev;120
getdisciplined;25
Entrepreneur;70
firefoxCoders;0
GetOutOfBed;40
investing;140
marketing;40
SEO;35
startups;30
BuyItForLife;100
Documentaries;200
Health;150
engineering;150
Physics;150
compsci;50
worldnews;750
atheism;3000
comics;1500
gadgets;100
wikipedia;300
meditation;80
music;1500
videos;3000
AskReddit;2000
blog;0
AskWomen;300
Design;70
explainlikeimfive;300
firefox;20
fitness;200
es;20
cogsci;200
DesignPorn;40
django;12
browsers;10
bicycling;300
askscience;130
fossworldproblems;30
Frugal;250
freelance;10
GetMotivated;400
geek;1000
javascript;20
LifeProTips;2000
linux;200
malefashionadvice;300
gainit;100
MTB;50
node;12
opensource;100
philosophy;140
productivity;40
Python;32
science;520
shutupandtakemymoney;500
snowboarding;200
spain;10
Survival;100
technology;1200
todayilearned;2000
travel;60
typography;40
Ubuntu;100
vim;20
web_design;50
webdev;40"

sep=2
if [ $# -ge 1 ]
then
    sep=$1
fi

for elm in $reddits
do
    data=(${elm//;/ })
    reddit=${data[0]}
    ups=${data[1]}
    echo "Procesando feed $reddit"
    curl -s "http://hoyga.com/redditfeed/redditfeed.php?reddit=$reddit&ups=$ups" > "$reddit.xml"
    sleep $sep
done
