#!/bin/bash

cd /var/www/hoyga/r

sep=2
if [ $# -ge 1 ]
then
    sep=$1
fi

echo '<?xml version="1.0" encoding="UTF-8"?>

<opml version="1.0">
    <head>
        <title>Reddit feed subs</title>
    </head>
    <body>
        <outline text="reddit" title="reddit">' > feeds.opml

dlr(){
    reddit=$1
    ups=$2
    echo "Procesando feed $reddit"
    curl "https://feedly.dvdbng.com/r/$reddit.xml?votes=$2" > "$reddit.xml"

    echo "<outline type='rss' text='Reddit feed for $reddit' title='Reddit feed for $reddit' xmlUrl='http://hoyga.com/r/${reddit}.xml' htmlUrl='http://reddit.com/r/$reddit'/>" >> feeds.opml
    sleep $sep
}

# copy(Array.from($('#srList tbody tr a')).map(x => x.textContent.toLowerCase()).sort().join('\n'))


dlr askhistorians 800
dlr askreddit 2000
dlr askscience 130
dlr askwomen 300
dlr atheism 3000
dlr bitcoin 500
dlr blog 0
dlr btc 400
dlr cryptocurrency 300
dlr dataisbeautiful 1000
dlr depthhub 200
dlr digitalnomad 30
dlr diy 1500
dlr documentaries 200
dlr engineering 150
dlr entrepreneur 70
dlr ethtrader 100
dlr europe 500
dlr explainlikeimfive 300
dlr firefox 200
dlr firefoxcoders 0
dlr frugal 650
dlr futurology 1000
dlr gadgets 200
dlr geek 1200
dlr health 170
dlr investing 240
dlr iota 200
dlr javascript 90
dlr lifeprotips 2800
dlr linux 300
dlr machinelearning 100
dlr marketing 150
dlr music 1900
dlr physics 200
dlr programming 100
dlr python 50
dlr nanocurrency 170
dlr science 570
dlr selfdrivingcars 50
dlr showerthoughts 3500
dlr spacex 200
dlr spacexlounge 150
dlr spain 100
dlr startups 100
dlr survival 500
dlr technology 1200
dlr ted 50
dlr thoriumreactor 12
dlr todayilearned 2300
dlr travel 500
dlr typography 100
dlr ubuntu 500
dlr videos 3000
dlr vim 70
dlr web_design 60
dlr webdev 50
dlr wikipedia 300
dlr worldnews 750

echo "
        </outline>
    </body>
</opml>" >> feeds.opml
